### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-pytorch-live - Not found

### ISSUE THREAD

**Issue by spinoza1791** [facebookresearch/playtorch#105]
### Tutorial Select

Get Started Manually

### Feedback

The initial template has an internal typo referencing the wrong destination:

npx react-native init myapp --template react-native-template-pytorch-live

...
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-pytorch-live - Not found
...
Output error shows an extra "react-native-template-" added to the URL, which is incorrect. 

The template code should instead point to: 
https://registry.npmjs.org/react-native-template-pytorch-live

**Comment by chrisklaiber** [comment]
Hello @spinoza1791, thank you for the bug report. I wasn't able to reproduce this issue. Is it still happening for you?
```
% npx --version
6.14.4

% npx react-native init myapp --template react-native-template-pytorch-live

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing CocoaPods dependencies (this may take a few minutes)


  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/crk/tmp/myapp" && npx react-native run-android

  Run instructions for iOS:
    • cd "/Users/crk/tmp/myapp" && npx react-native run-ios
    - or -
    • Open myapp/ios/myapp.xcworkspace in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.
```

**Comment by spinoza1791** [comment]
Thank you, I'm still seeing this:
![image](https://user-images.githubusercontent.com/26606744/183793189-0e115ae0-cd0e-405e-b688-f51b200873ad.png)

I don't have issues installing any other unrelated template like expo, etc. Any idea why the URL is getting the extra "react-native-template-react-native-template-pytorch-live"

**Comment by spinoza1791** [comment]
Found a workaround. This command works:
npx react-native init myapp --template **pytorch-live**
![image](https://user-images.githubusercontent.com/26606744/183794789-2a2f16ae-5023-43e8-b443-d6271e9ff3d6.png)

**Comment by chrisklaiber** [comment]
Hmm, I wonder if this could be due to the version of `react-native` being used. The old code used to add the extra prefix.

```
% npx react-native --version
5.0.1
```

This older version of react-native did use the extra prefix: https://github.com/react-native-community/cli/issues/605#issuecomment-517627583 and the user on that thread found they were running with an older client in the npm cache. The `npx` command will try to fetch the latest version.

**Comment by spinoza1791** [comment]
I believe this is a cli install issue (not a playtorch issue) with solutions ref here: https://github.com/react-native-community/react-native-template-typescript/issues/80
