### ISSUE TITLE
get a error when run first tutorial - normalize(tensor)

### ISSUE THREAD

**Issue by NgoVanDau** [facebookresearch/playtorch#159]
### Version

0.2.2

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

Unhandled promise rejection Error: "Exception in HostFunction: isString() INTERNAL ASSERT FAILED at "/data/users/atalman/pytorch/aten/src/ATen/core/ivalue_inl.h":2111, please report a bug to PyTorch. Expected String but got InvalidTag(-1005520576)
  
  Debug info for handle(s): debug_handles:{-1}, was not found.
  
Exception raised from toStringRef at /data/users/atalman/pytorch/aten/src/ATen/core/ivalue_inl.h:2111 (most recent call first):
(no backtrace available)" in Error: Exception in HostFunction: isString() INTERNAL ASSERT FAILED at "/data/users/atalman/pytorch/aten/src/ATen/core/ivalue_inl.h":2111, please report a bug to PyTorch. Expected String but got InvalidTag(-1005520576) <<    <<   Debug info for handle(s): debug_handles:{-1}, was not found. <<   
...

### Code example, screenshot, or link to repository

export var T = torchvision.transforms;
const mean = [0.485, 0.456, 0.406];
const std = [0.229, 0.224, 0.225];
export var classifyImage = async function (image) {
	var width = image.getWidth ();
	var height = image.getHeight ();
	var blob = media.toBlob (image);
	console.log ('blob = ', blob);
	tensor = torch.fromBlob (blob, [height, width, 3]);
	console.log ('tensor from blob:', tensor);
	tensor = tensor.permute ([2, 0, 1]);
	console.log ('tensor permute:', tensor);
	tensor.div (255);
	console.log ('tensor div:', tensor);
	// Center crop the image tensor to a square
  const cropValue = Math.min(width, height);
  const centerCrop = T.centerCrop(cropValue);
  tensor = centerCrop(tensor);
  console.log ('tensor centercrop:', tensor);

  const normalize = T.normalize(mean, std);
  tensor = normalize(tensor);
  console.log ('tensor normalize:', tensor);

	
	var resize = T.resize (224);
	tensor = resize (tensor);
	console.log ('tensor resize:', tensor);
	
	tensor = tensor.unsqueeze (0);
	console.log ('tensor squeeze:', tensor);
	return tensor.shape;
};

**Comment by raedle** [comment]
@NgoVanDau, please provide a reproducible end-to-end example, which should include the following:

* A model to reproduce the reported issue
* JavaScript code that loads the model and runs inference

Thank you!

**Comment by NgoVanDau** [comment]
Hi raedle, 
I'm using Transcrypt to translate my python code to react native. First of all, playtorch is easey to use and i am very interesting to it.
I try to run first your tutorial  - Image classification, log throw a error, so i print step by step variable. This is my snack: [https://snack.expo.dev/@dau123/imagenormaliize].
please tell me how to solve it.
By the way, when i code:
x = torch.rand([2])
console.log(x.data)
it print a function, not a data of x.
please tell me how to see the data of x.

**Comment by raedle** [comment]
@NgoVanDau, the issue with the `normalize` function is that the `dtype` of the input tensor needs to be `float32`, but the `dtype` in the provided Snack is `uint8`. There is a `tensor.div(255)` which would auto-convert the `dtype` from `uint8` to `float32`. However, the returned is never assigned to `tensor` (i.e., `tensor.div(255)` is not an in-place operation).

I changed the code in your Snack from:

```
export var classifyImage = async function (image) {
	var width = image.getWidth ();
	var height = image.getHeight ();
	var blob = media.toBlob (image);
	console.log ('blob = ', blob);
	var tensor = torch.fromBlob (blob, [height, width, 3]);
	console.log ('tensor from blob:', tensor);
	tensor = tensor.permute ([2, 0, 1]);
	console.log ('tensor permute:', tensor);
	tensor = tensor.div (255);
	console.log ('tensor div:', tensor);
	var centerCrop = T.centerCrop (Math.min (width, height));
	tensor = centerCrop (tensor);
	console.log ('tensor centercrop:', tensor);
	var resize = T.resize (224);
	tensor = resize (tensor)
	console.log ('tensor resize:', tensor);
	var normalize = T.normalize ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]);
	tensor = normalize (tensor); //<-----------error here

	console.log ('tensor normalize:', tensor);
	tensor = tensor.unsqueeze (0);
	console.log ('tensor squeeze:', tensor);
	return tensor.shape;
};
```

to

```
export var classifyImage = async function (image) {
	var width = image.getWidth ();
	var height = image.getHeight ();
	var blob = media.toBlob (image);
	console.log ('blob = ', blob);
	var tensor = torch.fromBlob (blob, [height, width, 3]);
	console.log ('tensor from blob:', tensor);
	tensor = tensor.permute ([2, 0, 1]);
	console.log ('tensor permute:', tensor);
	tensor = tensor.div (255); //<----------- change here
	console.log ('tensor div:', tensor);
	var centerCrop = T.centerCrop (Math.min (width, height));
	tensor = centerCrop (tensor);
	console.log ('tensor centercrop:', tensor);
	var resize = T.resize (224);
	tensor = resize (tensor)
	console.log ('tensor resize:', tensor);
	var normalize = T.normalize ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]);
	tensor = normalize (tensor);

	console.log ('tensor normalize:', tensor);
	tensor = tensor.unsqueeze (0);
	console.log ('tensor squeeze:', tensor);
	return tensor.shape;
};
```

Example Snack that works: https://snack.expo.dev/@raedle/imagenormaliize-test

That said, your use case sounds interesting. I'd be curious to learn more about the motivation behind the translation from Python to RN :)

**Comment by NgoVanDau** [comment]
Thanks. It was run. Transcrypt is very interesting to translate python to Js and easy to do with React, React natvie :) because i like python.
[https://snack.expo.dev/@dau123/imagenormaliize](url)

How about the code asccording API:

const tensor = torch.rand([2]);
console.log(tensor.data, tensor[0].data);
// [0.8339180946350098, 0.17733973264694214], [0.8339180946350098]

but it log:
function data() { [native code] } function data() { [native code] }

**Comment by NgoVanDau** [comment]
Ohw, Thanks.
Please repair API. Thanks for your support.
