### ISSUE TITLE
Error when run QA toturial

### ISSUE THREAD

**Issue by NgoVanDau** [facebookresearch/playtorch#163]
### Version

0.2.2

### Problem Area

react-native-pytorch-core (core package)

### Code example, screenshot, or link to repository

Dear Playtorch Team,
When i run program according your toturial (I program by transcrypt), it can't show answer.
Please tell me why it, and at line 15 of code, it warning that download now is deprecated (MobileModel.download(MODEL_URL) )
here is my snack:
[https://snack.expo.dev/@dau123/questionanswer](url)

**Comment by raedle** [comment]
@NgoVanDau, here is a working example with changes marked as inline comments:

```
var __name__ = 'torchApp.QuestionAnswer.QuestionAnswer';
export var pytorch = require ('react-native-pytorch-core');
export var torch = pytorch.torch;
export var MobileModel = pytorch.MobileModel;
export var text = pytorch.text;
export var BERT = require ('../BERTVocab.json');
export var tokenizer = new text.WordPieceTokenizer (dict ({'vocab': BERT.vocab}));
export var MODEL_URL = 'https://github.com/facebookresearch/playtorch/releases/download/v0.1.0/bert_qa.ptl';
export var model = null;
export var answerQuestion = async function (sourceText, question) {
  console.log('model = ', model);
	if (model == null) { // <<-- change to `model == null`. The model variable is `undefined` and not null despite being assigned null. You can see this with the console.log statement above. Generally, `model === null` should have worked, and I don't if this is an artifact due to Transcrypt (I don't know Transcrypt)
		var filePath = await MobileModel.download(MODEL_URL); // <<-- Use download function. MobileModel(MODEL_URL) doesn't work
		console.log ('load model:', filePath);
		var model = await torch.jit._loadForMobile (filePath);
		console.log ('model = ', model);
	}
  console.log ('model = ', model);
	var inputText = '[CLS] {} [SEP] {} [SEP]'.format (question, sourceText);
	var tokens = tokenizer.encode (inputText);
	var inputs = torch.tensor ([tokens], {dtype: torch.int}); // <<-- Change this to ideomatic JavaScript. JavaScript doesn't have kwargs, so it needs to be in object notion
  console.log('inputs:', inputs)
	var output = await model.forward (inputs);
	console.log ('output = ', output);
	var startId = output.start_logits.argmax ().item ();
	var endId = output.end_logits.argmax ().item ();
	var answer = tokenizer.decode (tokens.slice (startId, endId + 1));
	return answer;
};
```

PlayTorch Snack: https://snack.expo.dev/@raedle/questionanswer-test

You can ignore the warning about `MobileModel.download` or use a different way to download the PyTorch Mobile model onto the device

**Comment by NgoVanDau** [comment]
Thanks @raedle.
It run, but very slow. can you optimize to increase speed in inference.
it my code: [https://snack.expo.dev/@dau123/questionanswer](url).
My transcrypt code,is it easy?: 
**_async def answerQuestion(sourceText, question):
    if model == None:
        
        filePath = await MobileModel.download(MODEL_URL)
        #console.log('load model:', filePath)
        model = await torch.jit._loadForMobile(filePath)
        #console.log('model = ', model)
    
    inputText = f'[CLS] {question} [SEP] {sourceText} [SEP]'
    tokens = tokenizer.encode(inputText)
   
    inputs = torch.tensor([tokens], torch.int)

    output = await model.forward(inputs)
    console.log('output = ', output)

    startId = output.start_logits.argmax().item()
    endId = output.end_logits.argmax().item()
    answer = tokenizer.decode(tokens.slice(startId, endId + 1))
     
    return answer_**

**Comment by raedle** [comment]
Model training and model optimization is out of scope of PlayTorch. If you want to train a custom model and optimize for mobile (e.g., quantize), I recommend looking at the PyTorch Mobile documentation: https://pytorch.org/mobile/home/
