### ISSUE TITLE
Web/wasm support?

### ISSUE THREAD

**Issue by josephrocca** [facebookresearch/playtorch#171]
### Area Select

react-native-pytorch-core (core package)

### Description

In [this comment](https://github.com/facebookresearch/playtorch/issues/20#issuecomment-1001924902) it was mentioned that support for the web platform (by exposing libtorch via wasm) was out of the scope of the project. Just checking in to see if this has changed, by chance? The web is increasingly becoming a viable target for powerful apps thanks to wasm -- and WebGPU is just around the corner (probably early next year in Chromium-based browsers).

Note that I'm no stranger to getting PyTorch models working on the web via ONNX (e.g. [recent example](https://github.com/josephrocca/SimVP-web)) - it's just that I think the PyTorch and web ecosystems would benefit a lot if this process were made easier.

Please feel free to unceremoniously close this issue if the web is still definitely out of the scope of the project. I'll check in again every year or two 😅

**Comment by raedle** [comment]
@josephrocca, WASM/browser support for PlayTorch is out of scope unless someone from the open source community is interested in leading this effort. I can advise, but don't have experience with WASM.

Alternatively and depending on your intent, there is [shumai](https://github.com/facebookresearch/shumai), which is a differentiable tensor library for JavaScript using Bun. AFAIK, it supports Bun only, but I've seen some discussions around browser support in a couple of issues in that repo.

cc @bwasti

**Comment by josephrocca** [comment]
No problem - thanks for letting me know about shumai. Doesn't look like it'll suit this particular use case, but exciting to see they're adding WebGPU support!
