### ISSUE TITLE
Tensor assign at index

### ISSUE THREAD

**Issue by lusinlu** [facebookresearch/playtorch#172]
### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

Hi! if Im not wrong, currently it is not possible to assign a tensor at the index, i.e. this code will fail on the last line of assignment
```
images = // some array of Images
batch_size = 10  
var batch_tensor = torch.zeros([batch_size, 3, 224, 224])
for(var idx=0; idx<images.length;idx++)
    image = images[idx]
    height = image.getHeight();
    width = image.getWidth();
    
    const blob = media.toBlob(image);
    let tensor = torch.fromBlob(blob, [height, width, 3]);
    tensor = tensor.permute([2, 0, 1]);
    tensor = resize(tensor);
    batch_tensor[idx] = tensor
```

### Expected Results

Is it possible to have a tensor assign operation to work, or are there some other methods for creating a batch of images?

**Comment by raedle** [comment]
@lusinlu, that's correct. It is not possible to assign a tensor using the [Tensor Indexing API](https://pytorch.org/cppdocs/notes/tensor_indexing.html).

However, it should be possible by implementing the [`Tensor.index_put`](https://pytorch.org/cppdocs/api/classat_1_1_tensor.html#_CPPv4N2at6Tensor10index_put_E8ArrayRefIN2at8indexing11TensorIndexEERK6Tensor) function in [`TensorHostObject`](https://github.com/facebookresearch/playtorch/blob/main/react-native-pytorch-core/cxx/src/torchlive/torch/TensorHostObject.cpp) by overriding the JSI [`HostObject.set`](https://github.com/facebook/hermes/blob/main/API/jsi/jsi/jsi.h#L135-L139) function.

This is analogous to the [`Tensor.index`](https://pytorch.org/cppdocs/api/classat_1_1_tensor.html#_CPPv4NK2at6Tensor5indexE8ArrayRefIN2at8indexing11TensorIndexEE) implementation in the [`TensorHostObject.get`](https://github.com/facebookresearch/playtorch/blob/main/react-native-pytorch-core/cxx/src/torchlive/torch/TensorHostObject.cpp#L719-L735) function.

I can advise if you want to take a stab and submit a PR!

**Comment by raedle** [comment]
@lusinlu, alternatively, it is possible to concatenate tensors with the [`torch.cat`](https://playtorch.dev/docs/next/api/core/interfaces/torchlive_torch.torch/#cat) function.

```typescript
const tensor1 = torch.tensor(
  [
    [
      [1, 2],
      [3, 4],
      [5, 6],
    ],
  ],
  { dtype: torch.uint8 }
);
const tensor2 = torch.tensor(
  [
    [
      [7, 8],
      [9, 10],
      [11, 12],
    ],
  ],
  { dtype: torch.uint8 }
);
const tensor = torch.cat([tensor1, tensor2]);
console.log(tensor.shape);
console.log([...tensor.data()]);
```

```
[2,3,2]
[1,2,3,4,5,6,7,8,9,10,11,12]
```

Check this PlayTorch example: https://snack.playtorch.dev/@raedle/tensor_cat

**Comment by raedle** [comment]
I submitted PR #174 as working draft for the "inplace put" Tensor Indexing API

**Comment by lusinlu** [comment]
Hi @raedle ! Many thanks for such a prompt response and for the implementation. Indeed, the concat also can do the job, thanks for pointing out to it.
