### ISSUE TITLE
error when trying to use MediaLibrary.usePermissions() 

### ISSUE THREAD

**Issue by qoientlmn** [facebookresearch/playtorch#176]
### Version

v0.2.2

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce
Tested on ios device with Playtorch app using expo (android device doesn't work as well)

1.package.json
{
  "dependencies": {
    "react-native-pytorch-core": "0.2.2",
    "react-native-safe-area-context": "4.3.1",
    "expo-media-library": "~14.2.0"
  }
}
2. in App.tsx, 
import * as MediaLibrary from 'expo-media-library';

3.in export default function in App.tsx,
const [status, requestPermission] = MediaLibrary.usePermissions();

4.Error occurs
Error Message : App.tsx (0:1) `new NativeEventEmitter()` requires a non-null argument. (Device)

### Expected Results

Shows Alert if you're going to allow permission for this app to use in this device.

**Comment by raedle** [comment]
@qoientlmn, the PlayTorch app does not include the native code for `expo-media-library`, which means it can't be used with the PlayTorch app.

However, you can build your own app following instructions in the tutorial [Expo App](https://playtorch.dev/docs/next/tutorials/get-started-expo-app/). Then, after `npx expo install react-native-pytorch-core` also run `npx expo install expo-media-library`. This will include the `expo-media-library` in the app build.

Alternatively, the [PlayTorch app source code is open source](https://github.com/facebookresearch/playtorch/tree/main/app), and we are open to accepting PRs from the community. Submit a PR that adds the `expo-media-library` to the app, and I'll have a look if we merge it for the next version update of the PlayTorch app (version `0.1.3`).
