### ISSUE TITLE
Use Playtorch App with local expo[not snack]

### ISSUE THREAD

**Issue by kevinz8866** [facebookresearch/playtorch#192]
### Tutorial Select

Get Started

### Feedback

I see that we can use the PlayTorch App with Expo Snack. But it seem like the app can only recognize the QR code generated by Expo Snack but not if it is generated a local expo environment like in VSCode. So is it currently not supported to use the PlayTorch app with local expo? Are you plan to develop that in the future? Thanks!

**Comment by raedle** [comment]
Hi @kevinz8866, the PlayTorch app can only scan QR codes on Expo Snack, and it doesn't work with the Expo dev client.

However, PlayTorch supports Expo config plugins, and creating a custom client is relatively simple to achieve. There is a tutorial on the PlayTorch website: [Expo App](https://playtorch.dev/docs/tutorials/get-started-expo-app/)

**Comment by kevinz8866** [comment]
Hi @raedle, thanks for getting back to me. I see that the tutorial on using Expo app but the issue is that when I do `npm run:ios` lets say, the app is in a react native environment and one of my custom module that only works for expo is no longer working. But that is not a pressing issue for me as I can come up with a version that is compatible with react native. 

Is supporting Expo dev client with the PlayTorch App part of your future plan? Thanks.

**Comment by raedle** [comment]
There are no plans currently to support Expo dev client with the PlayTorch app. However, this is not the first time this was mentioned, so the community would definitely benefit from it. We do accept PRs for supporting Expo dev client

**Comment by kevinz8866** [comment]
Got it! I would try to figure out how to make it work on Expo dev client. Thank you for the helpful information.
