### ISSUE TITLE
Load Image from link

### ISSUE THREAD

**Issue by BILLXZY1215** [facebookresearch/playtorch#196]
### Area Select

react-native-pytorch-core (core package)

### Description

Hi, I'm wondering if it is possible to input an image url (native storage on mobile) rather than capture an image, to transfer the link to the `Image` object? Then we can do some image classification tasks more easliy.

**Comment by raedle** [comment]
@BILLXZY1215,are you looking to use an image picker to select images from the device's camera roll?

If yes, then the answer is "yes". There is an example PlayTorch Snack:

https://snack.playtorch.dev/@raedle/image-classification-with-image-picker
