### ISSUE TITLE
iOS does not support all types in model spec

### ISSUE THREAD

**Issue by mdwelsh** [facebookresearch/playtorch#26]
### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

1. Write a model spec JSON with an "unpack" type of "tuple" or "list", as described in the documentation here:
https://pytorch.org/live/docs/api/model-spec/#unpack-output-post-processing

2. Attempt to execute this model on iOS.

### Expected Results

The model should execute and return the tuple or list as a return value.

Instead, the model returns an InvalidUnpackType error, which seems to be returned by:

https://github.com/pytorch/live/blob/main/react-native-pytorch-core/ios/ML/Processing/BaseIValuePacker.swift#L79

At minimum the documentation should probably point out that these types are not currently supported on iOS.

### Code example, screenshot, or link to repository

<img width="363" alt="Screen Shot 2022-01-03 at 10 08 49 PM" src="https://user-images.githubusercontent.com/996692/148016649-75fa078b-e0ae-47ec-9188-c96db69ff1d2.png">

**Comment by raedle** [comment]
Thanks for reporting this and for submitting PR #27 to report the differences in the API docs, @mdwelsh!

**Comment by JohnZcp** [comment]
So instead of using tuple and list, how can construct my "unpack" part for the tuple of the lists?

**Comment by raedle** [comment]
@mdwelsh, @JohnZcp, and @kyleliang919, the `react-native-pytorch-core` release candidate `v0.2.0-rc.2` has a PyTorch-inspired API to support a more flexible data processing. 

Tuples are now supported on both platforms Android and iOS with the PyTorch Live JavaScript API. For example, the following will run inference and destruct the output (tuple) into `y` and `z`.

```javascript
const x = torch.rand([1, 3, 600, 600]);
const output = await model.forward<Tensor, Tensor[]>(x);
const y = output[0];
const z = output[1];
// or const [y, z] = output;
```

Check out this example for YOLOv5s integration with PyTorch Live [ObjectDetection.ts](https://github.com/raedle/YOLOExample/blob/main/src/ObjectDetection.ts#L71)!

More details on available ops are is in the API docs:

* https://pytorch.org/live/docs/next/api/core/interfaces/torchlive_torch.torch/
* https://pytorch.org/live/docs/next/api/core/interfaces/torchlive_torch.tensor/

Feel free to reach out on Discord or here if any ops are missing for your use cases!

**Comment by chrisklaiber** [comment]
Closing this issue out since the packer / unpacker approach was removed with 0.2.2. Check out the PyTorch-inspired API in the README as an alternative that avoids these issues: https://github.com/facebookresearch/playtorch/tree/main/react-native-pytorch-core#example-usage
