### ISSUE TITLE
Model Spec for MobileNet Classes

### ISSUE THREAD

**Issue by awcchungster** [facebookresearch/playtorch#37]
### Tutorial Select

Prepare Custom Model

### Feedback

If we follow the tutorial verbatim and take the MobilenetV3 images directly from pretrained, how do we get the MobileModel function to return the top 5 classes and confidence scores?

https://pytorch.org/live/docs/api/model-spec/

**Comment by raedle** [comment]
Thanks for reaching out @awcchungster. PyTorch Live currently has a limited set of ops that are supported in the processing specification, and it doesn't support `topk`. It is possible to add additional ops to the PyTorch Live model specification. Besides `topk`, are there any other ops that you are considering to use?

Also, we will add functionality to PyTorch Live that will eventually remove these constraints entirely (e.g., by providing a JavaScript API that's backed by libTorch C++). At the moment, we are hashing out the API details and haven't pushed the code to GitHub yet, but here is an example of what the API currently looks like for retrieving top 5 results of a MobileNetV3 model inference result:

```javascript
let imageTensor = torchvision.tensorFromImage(frame, 480, 640);
imageTensor = imageTensor.permute([2, 0, 1]);
imageTensor = torch.unsqueeze(imageTensor, 0);

let output = module.forward(imageTensor);

let result = torch.squeeze(output);
const softmaxResult = torch.softmax(result, 1);
const [_values, indices] = torch.topk(softmaxResult, 5);

indices.data.forEach((idx: number) => {
  const cls = IMAGE_CLASSES[idx];
  console.log(cls);
});
```

(API subject to change)

Please let us know if you have feedback on this approach!

**Comment by awcchungster** [comment]
Hi @raedle! Thanks for responding timely manner. I found a bounding box example for mobilenet that I plan on testing next. After that I plan to do a segmentation model. 

Are there examples of how to take a mobile net segmentation model results and apply it to PTL?

**Comment by awcchungster** [comment]
Also, the APIs change a little too frequently. I understand this is all pre v1, so at a minimum putting this into a change log seems like a reasonable request. 

I ran into a number of occurrences. For example, the [NPM documentation](https://www.npmjs.com/package/react-native-pytorch-core) didn't work. I had to dig through the Github to understand the class name changes that were done.

**Comment by chrisklaiber** [comment]
Closing this issue out since the "Live Spec" approach was removed with 0.2.2. Check out the PyTorch-inspired API in the README as an alternative that avoids these issues: https://github.com/facebookresearch/playtorch/tree/main/react-native-pytorch-core#example-usage

As an additional note, `topk` is available in the new API: https://playtorch.dev/docs/api/core/interfaces/torchlive_torch.tensor/#topk
