### ISSUE TITLE
Project Initializition Error

### ISSUE THREAD

**Issue by kerbaypapilon** [facebookresearch/playtorch#67]
### Tutorial Select

Get Started Manually

### Feedback

I think the command; 
`npx react-native init MyFirstProject --template react-native-template-pytorch-live`

should be as;
`npx react-native init MyFirstProject --template pytorch-live`

**Comment by chrisklaiber** [comment]
This appears to be the same underlying issue as #105. There was an older version of the React Native CLI that would prefix "react-native-template-" and cause an issue with the downloading. The solution is to upgrade the globally installed React Native CLI version.

I will close out this issue, but feel free to reopen if needed.
