### ISSUE TITLE
Can't find variable: __torchlive__

### ISSUE THREAD

**Issue by andydam452** [facebookresearch/playtorch#69]
After install package, I got this error when run yarn start.
I add package to existing app which using bare react native.
Current RN ver: 0.66.0
React ver: 17.0.2

![image](https://user-images.githubusercontent.com/44116015/178721176-b7f03464-4039-401d-a960-521727025c23.png)

**Comment by fazzysyed** [comment]
the app was working perfectly then suddenly i am also got this error don't know how to fix it

**Comment by andydam452** [comment]
@fazzysyed Hi, Did you update the package or something?

**Comment by raedle** [comment]
@andydam452 is this happening on Android?

What is the `react-native-pytorch-core` package version that's used in the project?

From the error, it looks like the C++ parts of PyTorch Live aren't registered/loaded. We updated the documentation ["Add Package to Existing App"](https://pytorch.org/live/docs/next/tutorials/add-package/), which explains what the React Native project setup should look like for PyTorch Live to function correctly.

Can you give this particular documentation try?

**Comment by kkmehta03** [comment]
Having the same issue. I'm trying to add it in my existing expo application, just followed the `yarn add react-native-pytorch-core` and tried to run it on iOS but received the same error

**Comment by raedle** [comment]
@kkmehta03, the Expo managed workflow uses the Expo Go app to run the JavaScript code. You can either use [Expo Custom Development Clients](https://docs.expo.dev/development/introduction/) or eject from Expo (`yarn eject`)

**Comment by kkmehta03** [comment]
@raedle, thanks for your response! Is there any other way to install pytorch core into Android without ejecting expo? because with expo, we dont get access to the build gradle files. however, my app has a lot of expo dependencies. Any suggestions?

**Comment by raedle** [comment]
@kkmehta03, I'm not aware of any other option besides implementing an Expo Config Plugin (https://docs.expo.dev/guides/config-plugins).

The PlayTorch repo has an outdated [config plugin](https://github.com/facebookresearch/playtorch/blob/main/react-native-pytorch-core/src/expo-plugin/withPyTorchCore.ts) that works with `react-native-pytorch-core` version `0.1.3` and for React Native `0.64.3`.

We welcome a PR for an updated Expo config plugin!

cc @justinhaaheim, @byCedric

**Comment by chrisklaiber** [comment]
@kkmehta03 now with the release of 0.2.1 our Expo config plugin might now be working for you. See the expo steps in my comment here: https://github.com/facebookresearch/playtorch/issues/73#issuecomment-1217099999

**Comment by chrisklaiber** [comment]
Closing this out with the given solution. Feel free to reopen if necessary.
