### ISSUE TITLE
Can't run the app on my phone or the 

### ISSUE THREAD

**Issue by tnoulas** [facebookresearch/playtorch#7]
### Tutorial Select

Get Started

### Feedback

When I run 
npx torchlive-cli init MyFirstProject
I get the following exception. This happens when I both try to run while having a phone connected or the emulator. I am using the latest version of android studio. 

FAILURE:‎ Build‎ failed‎ with‎ an‎ exception.

*‎ What‎ went‎ wrong:
Execution‎ failed‎ for‎ task‎ ':app:installDebug'.
>‎ java.util.concurrent.ExecutionException:‎ com.android.builder.testing.api.DeviceException:‎ com.android.ddmlib.InstallException:‎ INSTALL_FAILED_INVALID_APK:‎ Scanning‎ Failed.:‎ Package‎ /data/app/org.pytorch.live.example-oieYaFbXt6dMki1MKv4QNA==/base.apk‎ code‎ is‎ missing

*‎ Try:
Run‎ with‎ --stacktrace‎ option‎ to‎ get‎ the‎ stack‎ trace.‎ Run‎ with‎ --info‎ or‎ --debug‎ option‎ to‎ get‎ more‎ log‎ output.‎ Run‎ with‎ --scan‎ to‎ get‎ full‎ insights.

*‎ Get‎ more‎ help‎ at‎ https://help.gradle.org

BUILD‎ FAILED‎ in‎ 17s

‎ ‎ ‎ ‎ at‎ makeError‎ (/Users/anastasiosnoulas/MyFirstProject/node_modules/execa/index.js:174:9)
‎ ‎ ‎ ‎ at‎ /Users/anastasiosnoulas/MyFirstProject/node_modules/execa/index.js:278:16
‎ ‎ ‎ ‎ at‎ processTicksAndRejections‎ (internal/process/task_queues.js:93:5)
‎ ‎ ‎ ‎ at‎ async‎ runOnAllDevices‎ (/Users/anastasiosnoulas/MyFirstProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
‎ ‎ ‎ ‎ at‎ async‎ Command.handleAction‎ (/Users/anastasiosnoulas/MyFirstProject/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)

**Comment by liuyinglao** [comment]
Hey Tassos,

Thanks for reporting the issue! The build error message doesn't seems to be clear where may go wrong -- may I ask for your help to identify the issue with the following check?
1. when you "npx torchlive-cli init <project name>", do you see any error reported?
2. could you run in your terminal "ls <project name>/models" and paste the output here?
3. could you also try to run "npx torchlive-cli run-android" within the "<project name>/" directory?

**Comment by tnoulas** [comment]
Hi, 

the above happened only when I used the MyFirstProject instructions. 

When instead I try to run this tutorial https://pytorch.org/live/docs/tutorials/image-classification
it all worked great!

Back to your questions

2. 
(base) AnastasiossMBP2:MyFirstProject anastasiosnoulas$ ls ./models/
bert_qa.ptl				mnist.ptl				requirements.txt
bert_qa.ptl.live.spec.json		mnist.ptl.live.spec.json		resnet18.ptl
detr_resnet50.ptl			mobilenet_v3_large.ptl			resnet18.ptl.live.spec.json
detr_resnet50.ptl.live.spec.json	mobilenet_v3_large.ptl.live.spec.json	venv
error.log				mobilenet_v3_small.ptl
make_models.py				mobilenet_v3_small.ptl.live.spec.json

3. That's what I did!

**Comment by raedle** [comment]
Hi @tnoulas,

If I understand correctly, the Image Classification tutorial worked for you, but running the commands in the Get Started tutorial fails. Is this correct?

Can you provide the output for the following commands:

* `npx torchlive-cli doctor`
* `npx react-native info`

It might be a shot in the dark, but try running `npx torchlive-cli clean` in the project directory and then re-run `npx torchlive-cli run-android`. It could be that there are some artifacts from previous Android builds that are causing an issue

**Comment by aaronespasa** [comment]
Hey @tnoulas,

Did you install all the dependencies and packages before executing the `init` command? If that's not the case, I encourage you to run the following command:

```bash
$ npx torchlive-cli setup-dev
```

You'll see that the previous command will also install both the Android SDK and the Android Emulator. But even when I did this, I still couldn't run the app on the Android Emulator. What was missing was to install Android Studio.

After you have executed the `setup-dev` command, install Android Studio: [Click on this link to go to the official webpage of Android Studio](https://developer.android.com/studio).

---
I'll summarize the steps you have to follow:

0. 
      - Make sure you have Ruby updated and added to PATH. Otherwise, CocoaPods will throw some errors ([Install Ruby on Your Mac](https://stackify.com/install-ruby-on-your-mac-everything-you-need-to-get-going/)).
      - I also think that the version 17 of Node have some conflicts, so downgrade Node to the version 16 ([StackOverflow - How to downgrade Node version](https://stackoverflow.com/questions/47008159/how-to-downgrade-node-version)).
      - The last thing of this step, upgrade Python to the version 3.9.9 and make sure the command `python3 -V` outputs Python 3.9.9 (Once [this pull request](https://github.com/pytorch/live/pull/9) is approved you will no longer have to worry about the python version).
1. Install all the necessary dependencies and packages:
```bash
$ npx torchlive-cli setup-dev
```
2. Install [Android Studio](https://developer.android.com/studio).
3. Now, you're ready to create the template for your project (remember, `python3 -V` has to output the version 3.9.9): 
```bash
$ npx torchlive-cli init TheNameOfMyProject
```

4. Now you're all set up! 🎉
    - However, make sure the models in the  TheNameOfMyProject/models/ folder have been built correctly (check that there are files that end with the extensión `.ptl`). Otherwise, you'll have to build them yourself. In this last case, run the following commands inside  the `models/` folder:
    - Activate the environment: `source venv/bin/activate`).
    - Install the necessary dependencies: `python3 -m pip install requirements.txt --no-cache-dir`.
    - Build the models: `python3 -W ignore make_models.py`

5. To run your app in Android, go to the `TheNameOfMyProject/ ` main folder. There you have 2 options:
     - Run the torchlive-cli command: `$ npx torchlive-cli run-android`.
     - If the terminal gets stuck in the execution, stop the command. Open two different terminal and execute this command `$ npx react-native start` in one terminal (this will open metro and will look for changes in your code to be applied in your app in real-time) and this other command `$ npx react-native run-android` to build the app on the Android emulator or on your phone.

The app should look like this at the beginning (and in the pointed section you can start to do your own projects 🧪):

![image](https://user-images.githubusercontent.com/39239895/144969062-62293dac-ddf8-4a86-a076-361bb6f18008.png)

I'm trying to make this project available for the M1 MacBooks and solving the problems stated in the 0. section. Let me know if you've any issue with any of the previous steps, I'll be happy to help you! 😊

**Comment by raedle** [comment]
@tnoulas, does this issue still exist in the latest release `0.2.0`?

**Comment by chrisklaiber** [comment]
Closing this issue since it has been quiet for a long time. Since it was first filed, we've released the PlayTorch app to make it easier to get started without a local development environment. Follow these instructions to get going: https://playtorch.dev/docs/tutorials/get-started/
