### ISSUE TITLE
Error: Could not convert downloaded file into Torch Module

### ISSUE THREAD

**Issue by vemusharan** [facebookresearch/playtorch#89]
### Version

 "dependencies": {
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-pytorch-core": "^0.1.3",
    "react-native-safe-area-context": "^4.2.5"
  },

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

When trying to get the inference from the model getting the error.

<img width="803" alt="Screenshot 2022-07-28 at 15 28 11" src="https://user-images.githubusercontent.com/70719854/181516916-33018b60-3640-4539-9f27-2ea0f0b04e24.png">

### Expected Results
<img width="796" alt="Screenshot 2022-07-28 at 15 31 33" src="https://user-images.githubusercontent.com/70719854/181517678-1f48b8fe-3bb8-4a1a-ae77-e50535c7b7aa.png">

### Code example, screenshot, or link to repository

The .ptl file is generated following the instructions provided in the (https://playtorch.dev/docs/0.1/tutorials/prepare-custom-model/) 

Here is the App.js
<img width="875" alt="Screenshot 2022-07-28 at 15 25 25" src="https://user-images.githubusercontent.com/70719854/181516308-46b07d34-4a24-4705-858a-d2dfc658896d.png">

**Comment by raedle** [comment]
Hi @vemusharan, from the screenshot that you provided, the code tries to load the `test.png` image from a macOS machine. This will not work. The `ImageUtil.fromFile` will only be able to load images from the mobile device's file system. You can either use `ImageUtil.fromBundle` or `ImageUtil.fromURL` (see [`ImageUtil` in docs](https://playtorch.dev/docs/0.1/api/core/modules/imagemodule/#imageutil)).

I would recommend using `react-native-pytorch-core` `0.2.0` instead of the `0.1.3` release (see [Get Started tutorial for `0.2.0`](https://playtorch.dev/docs/tutorials/get-started/))

**Comment by vemusharan** [comment]
Thanks a lot @raedle  for quick response, I tried to check with the `ImageUtil.fromURL` still I am getting the error. Please correct me if I am wrong, the `react-native-pytorch-core` `0.20` doesn’t allow us to deploy the model on mobile device ryt?

**Comment by raedle** [comment]
@vemusharan, the latest release `0.2.0` allows model bundling with the app. The way this works is as follows

```javascript
if (model == null) {
    const filePath = await MobileModel.download(require('./models/mobilenet_v3_small.ptl'));
    model = await torch.jit._loadForMobile(filePath);
}
```

For reference, this is similar to how it is proposed in #88. Let us know if you run into issues!

**Comment by vemusharan** [comment]
Thank you @raedl.  I noticed that in order to resolve the error, we need to switch to `torch 1.11.0`.  Below is the code..

**makemodel.py**

```
!pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html```


import torch
import torchvision
from pathlib import Path
from torch.utils.mobile_optimizer import optimize_for_mobile
model = torchvision.models.mobilenet_v3_small(pretrained=True)
model.eval()
scripted_model = torch.jit.script(model)
optimized_model = optimize_for_mobile(scripted_model)
spec = Path("live.spec.json").read_text()
extra_files = {}
extra_files["model/live.spec.json"] = spec
optimized_model._save_for_lite_interpreter("mobilenet_v3_small.ptl", _extra_files=extra_files)
print("model successfully exported")

**Comment by raedle** [comment]
Thanks for reporting back, @vemusharan!

I would recommend using the new PlayTorch SDK with the JavaScript API to do data processing as the live spec will be remove in the next version.

>Be aware that the image pre-processing and post-processing is now in JavaScript instead of using the live spec. Have a look at the [image classification tutorial](https://playtorch.dev/docs/tutorials/snacks/image-classification/) for data processing steps.

>For reference, this is similar to how it is proposed in https://github.com/facebookresearch/playtorch/issues/88. Let us know if you run into issues!

**Comment by vemusharan** [comment]
Thank you @raedle. New PlayTorch SDK with the JavaScript API is straightforward and developer-friendly. I'm working on a audio event classification task, Is it possible to read .wav file and convert it to tensor and pass the tensor as an input to the model using playtorch?
