### ISSUE TITLE
Error message in Object Detection

### ISSUE THREAD

**Issue by zenetio** [facebookresearch/playtorch#90]
### Tutorial Select

Prepare Custom Model

### Feedback

I have two points.
1. Please make the error messages more user-friendly. I was working with OD example and got and got an error. The error message had a lot of things but not easy to find out what or where the error occurred. Then after reading the message many times, I decided to do a trying search in the files using a variable name I found in the error message. I could find the variable and manage the issue. 
2. Advise the user where to find the additional assets not listed in the web project. For instance, in the OD example, after the inference process, I have a screen where the button "Take another picture" is exactly over the close button of my cell phone. So, when I try to take another picture, the app closes. So, I need to change the position of this button but could not find it in the files listed on the web page. I am guessing will need to try to search in the files stored in github.

**Comment by raedle** [comment]
Hi @zenetio, first of all, thank you for your feedback!

1. Absolutely! Please let us know what the error message and provide steps to reproduce the error/issue! This will help us identifying the issue and provide more user friendly error message with actionable feedback.
2. What is the device model on which you are seeing the issue? If you can, please provide a screenshot that shows the button underneath the close button.

Thank you!

**Comment by zenetio** [comment]
Hi @raedle , 
1. In file **objectDetector.js** I changed the variable name from bounds to boxes and then I got a compilation error. The error message was not clear to clarify where and why I was getting the error. I think it could be more assertive. 
2. My device is a Samsung Galaxy S9.  You can see in the screenshot that the OD app is drawing the button message exactly over the device button.
![od](https://user-images.githubusercontent.com/578337/181676160-57a15547-e2df-40a6-91c3-07c294f91d20.jpg)

**Comment by raedle** [comment]
1. If I understand correctly, you changed the following code in the `ObjectDetector.js` from

```javascript
// Adjust bounds to image size
const bounds = [
  x * imageWidth,
  y * imageHeight,
  boxWidth * imageWidth,
  boxHeight * imageHeight,
];

const match = {
  objectClass: COCO_CLASSES[maxIndex],
  bounds,
};
```

to

```javascript
// Adjust bounds to image size
const boxes = [
  x * imageWidth,
  y * imageHeight,
  boxWidth * imageWidth,
  boxHeight * imageHeight,
];

const match = {
  objectClass: COCO_CLASSES[maxIndex],
  boxes,
};
```

Is that correct?

2. Thanks for reporting the issue. If you are using the Expo Snack editor, you can change the `marginBottom` for the `resetButton` style in `screens/ResultScreen.js` to a higher number.

Full example for `screens/ResultScreen.js`:

```javascript
import * as React from "react";
import { useEffect, useRef, useState } from "react";
import {
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Platform,
} from "react-native";
import { Canvas } from "react-native-pytorch-core";

const objectColors = [
  "#FF3B30",
  "#5856D6",
  "#34C759",
  "#007AFF",
  "#FF9500",
  "#AF52DE",
  "#5AC8FA",
  "#FFCC00",
  "#FF2D55",
];

const textBaselineAdjustment = Platform.OS == "ios" ? 7 : 4;

export default function ResultsScreen({ image, boundingBoxes, onReset }) {
  const [ctx, setCtx] = useState(null);
  const [layout, setLayout] = useState(null);

  // This is a drawImage function wrapped in useCallback (for improving render performance)
  useEffect(
    () => {
      if (ctx != null && layout != null && image != null) {
        ctx.clearRect(0, 0, layout.width, layout.height);

        // Scale image to fit screen
        const imageWidth = image.getWidth();
        const imageHeight = image.getHeight();
        const scale = Math.max(
          layout.width / imageWidth,
          layout.height / imageHeight
        );
        const displayWidth = imageWidth * scale;
        const displayHeight = imageHeight * scale;
        const offsetX = (layout.width - displayWidth) / 2;
        const offsetY = (layout.height - displayHeight) / 2;
        ctx.drawImage(image, offsetX, offsetY, displayWidth, displayHeight);

        // draw bounding boxes and label them, if provided
        if (boundingBoxes) {
          ctx.font = `13px monospace`;
          ctx.fillStyle = "#000";
          ctx.textAlign = "left";

          boundingBoxes.forEach((boundingBox, index) => {
            const { objectClass, bounds } = boundingBox;
            const x = offsetX + bounds[0] * scale;
            const y = offsetY + bounds[1] * scale;
            const w = bounds[2] * scale;
            const h = bounds[3] * scale;

            const boxColor = objectColors[index % objectColors.length];
            ctx.strokeStyle = boxColor;
            ctx.lineWidth = 3;
            ctx.beginPath();
            ctx.rect(x, y, w, h);
            ctx.stroke();

            const textHorizontalPadding = 10;
            const textWidth =
              objectClass.length * 6 + 2 * textHorizontalPadding;
            ctx.strokeStyle = "#000";
            ctx.lineWidth = 25;
            ctx.lineCap = "round";
            ctx.beginPath();
            const textStartX = x + w / 2 - textWidth / 2;
            ctx.moveTo(textStartX, y);
            ctx.lineTo(textStartX + textWidth, y);
            ctx.stroke();

            ctx.fillStyle = "#fff";
            ctx.fillText(objectClass, textStartX, y + textBaselineAdjustment);
          });
          ctx.invalidate();
        }
      }
    },
    [ctx, layout, image, boundingBoxes] // dependencies for useCallback
  );
  return (
    <View style={styles.container}>
      <Canvas
        style={StyleSheet.absoluteFill}
        onLayout={(event) => {
          setLayout(event.nativeEvent.layout);
        }}
        onContext2D={setCtx}
      />
      <View style={styles.bottomContainer}>
        <TouchableOpacity onPress={onReset} style={styles.resetButton}>
          <Text style={styles.buttonLabel}>Take another picture</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  bottomContainer: {
    position: "absolute",
    width: "100%",
    bottom: 0,
    left: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  resetButton: {
    backgroundColor: "white",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 38,
  },
  buttonLabel: {
    color: "black",
    fontSize: 16,
    fontWeight: "bold",
  },
});
```

**Comment by zenetio** [comment]
Hi @raedle,
Yes, I changed the name bounds to boxes in **objectDetector.js** but I had no idea that I had to do the same in **ResultScreen.js** as well. That is the reason why I got the issue and the error message was not so friendly to help fix.
Regarding the "Take another picture" button, I changed the marginBottom value and now I can use it.
Thanks for the help.
