### ISSUE TITLE
Including LibTorchvision on Android

### ISSUE THREAD

**Issue by nh9k** [facebookresearch/playtorch#98]
### Area Select

react-native-pytorch-core (core package)

### Description

Hello, thanks for your contributions.

I encountered a error on react native android to loading custom ptl model.
I think this error can solve if i can include Libtorchvision from relavated issue on this: https://github.com/facebookresearch/playtorch/issues/64

How can i include it in my android application?

Please provide me any leads.
Thank you.

<br>

Error:
`{"message": "Following ops cannot be found. Please check if the operator library is included in the build. If built with selected ops, check if these ops are in the list. If you are a Meta employee, please see fburl.com/missing_ops for a fix. Or post it in https://discuss.pytorch.org/torchvision::nms ()
Exception raised from initialize_operators at /data/users/atalman/pytorch/torch/csrc/jit/mobile/function.cpp:89 (most recent call first):
(no backtrace available)"}`

**Comment by raedle** [comment]
Hi @nh9k, that's correct. The nms (non-maximum suppression) op is part of the Torchvision ops. The `react-native-pytorch-core` doesn't include the Torchvision ops, but they can be added to a project, if needed.

I created a repo for the D2Go model, which also requires Torchvision ops to run inference. I created a single commit for the changes that add Torchvision ops to Android and iOS. Have a look at this [commit in the `raedle/D2GoExample` repo](https://github.com/raedle/D2GoExample/commit/edc4677c64853a0fbb9f3ba52710eb11cd9df9a5)!

Note: for iOS it uses the `LibTorchvision-DONOTUSE` CocoaPod because the Torchvision ops `0.13.0` that are compatible with PyTorch `1.12` have not be released officially. They are coming soon, and in the meantime you can use the `LibTorchvision-DONOTUSE`, which are functionally equivalent to the upcoming release!

Hope that helps, and please report back if you are successful! Any feedback to the project is helpful for us to learn :)

Thank you!

**Comment by nh9k** [comment]
@raedle 
Thanks for your swift response.
It's very helpful example for me :)

If i have any questions, i would like to report back.
Thank you so much!

**Comment by nh9k** [comment]
@raedle I solved the error by referring to this commit, thank you!

**Comment by nh9k** [comment]
Hi, @raedle, my app crashes as soon as it starts on android from my another project after adding `Torchvision ops`.
The app gets successfully installed on both `android 11.0` and `12.0` with `x86_64`.

Other versions:
```python
react-native: 0.68.1
react-native-pytorch-core: 0.2.2
fbjni: 0.2.2

buildToolsVersion = "31.0.0"
minSdkVersion = 28
compileSdkVersion = 31
targetSdkVersion = 31

classpath("com.android.tools.build:gradle:7.0.4")
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
```

I also got the logs from `adb logcat`, but i don't guess what is the problem..

```python
I(  550:  594) Displayed com.testapp/.MainActivity: +1s706ms
D(  550:  589) Transition from ACTIVITY_LAUNCHED to ACTIVITY_FINISHED
D(  317:  369) claimShared: Ask to claim region [0x3f7be6000 0x3f7c32000]
I( 6391: 6457) Deleted sessionId[28109581411005750] from persistence.
D(  317:  369) claimShared: Ask to claim region [0x3f7c32000 0x3f7c7e000]
D(  317:  369) claimShared: Ask to claim region [0x3f7c7e000 0x3f7cca000]
W( 6391: 6432) Abort, client detached.
I( 6391: 6432) Should stop hotword detection immediately - false
D(  317:  369) claimShared: Ask to claim region [0x3f7c32000 0x3f7c7e000]
D(  317:  369) claimShared: Ask to claim region [0x3f7c7e000 0x3f7cca000]
D( 6515: 6547) libreactnativejni.so not found on /data/app/~~0MhswA8wesnbrmpUv45hIw==/com.testapp-YPr_a5WB3YiNmOrqC9YZ1w==/lib/x86_64
D( 6515: 6547) libreactnativejni.so found on DirectAPKSoSource: 4
V( 6515: 6561) No scoped database found
I(  550: 3952) oneway function results will be dropped but finished with status OK and parcel size 4
I(  550: 3952) oneway function results will be dropped but finished with status OK and parcel size 4
D( 6515: 6561) libtorchlive.so not found on /data/app/~~0MhswA8wesnbrmpUv45hIw==/com.testapp-YPr_a5WB3YiNmOrqC9YZ1w==/lib/x86_64
D( 6515: 6561) libtorchlive.so found on DirectAPKSoSource: 4
F( 6515: 6562) Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6562 (mqt_js), pid 6515 (com.testapp)
I( 6567: 6567) obtaining output fd from tombstoned, type: kDebuggerdTombstone
I(  293:  293) received crash request for pid 6562
I( 6567: 6567) performing dump of process 6515 (target tid = 6562)
F( 6567: 6567) *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

**Comment by raedle** [comment]
@nh9k, from the logcat logs it looks like that the shared object libraries aren't packaged correctly.

But generally, there are two parts that are important to add `torchvision_ops` to your app. See how this is done in the PlayTorch app:

1. Add the `torchvision_ops` to the app's [build.gradle](https://github.com/facebookresearch/playtorch/blob/main/app/android/app/build.gradle#L319-L320) (make sure the versions for `torchvision_ops` and `pytorch_jni_lite` are compatible)
2. Load the `torchvision_ops` shared object library *after* loading the `pytorch_jni_lite` shared object library (see [MainApplication.java]( https://github.com/facebookresearch/playtorch/blob/main/app/android/app/src/main/java/dev/playtorch/MainApplication.java#L70-L71))

**Comment by nh9k** [comment]
Hi, @raedle, always thank you so much!
This second part is helpful to me. :blush:  

I readed this comment from [MainApplication.java](https://github.com/facebookresearch/playtorch/blob/main/app/android/app/src/main/java/dev/playtorch/MainApplication.java#L70-L71), 
```python
 // Note: Loading the libraries have to happen after the SoLoader.init call
 // above and therefore can't be done in a static block. 
```
This means that loading this `CustomJSIModulePackage` as this code is not working?
```python
@Override
protected JSIModulePackage getJSIModulePackage() {
  return new CustomJSIModulePackage();
}
``` 

I don't understand what difference of this loading Package and SoLoader.loadLibrary. :cry:
